[project]
name = "zoedepth"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
  "scipy",
  "h5py",
]

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
include = ["zoedepth*"]
